Todos - #1 View
matej494/Marsiple pull request #12
Opened 2018-07-30 09:59 UTC by matej494

2018-07-31 07:08 UTC, dkulundzic requested changes
Looks great 👍 Minor nitpicks and one question.

Do you plan on making the Todo completion animated in a later PR? The Todos should animate as they go through state changes.

2018-07-31 07:08 UTC, dkulundzic commented on Marsiple/App/Todos/TodosViewController.swift
> +        let uncompleated = [Todo](repeating: Todo(id: 1, title: "Todo 1", completed: false, userId: 1), count: 10)
Typo `compleated` -> `completed`.

2018-07-31 07:08 UTC, dkulundzic commented on Marsiple/App/Todos/TodosViewController.swift
> +        let compleated = [Todo](repeating: Todo(id: 1, title: "Todo 2", completed: true, userId: 1), count: 10)
Typo `compleated` -> `completed`.

2018-07-31 07:08 UTC, dkulundzic commented on Marsiple/App/Todos/TodosViewController.swift
> +        todos[1 - indexPath.section].insert(removedTodo, at: todos[1 - indexPath.section].count)
That's an interesting approach (index calculation) 👍

2018-07-31 10:28 UTC, matej494 commented
I didn't know how to implement animation for this case so I planned to implement it later, but I've figured it out and it's coming in the next commit.

2018-08-02 07:26 UTC, dkulundzic requested changes
Looks good, but an improvement is necessary.

2018-08-02 07:26 UTC, dkulundzic commented on Marsiple/App/Todos/TodosViewController.swift
> +        let finishIndexPath = IndexPath(row: todos[1 - indexPath.section].count, section: 1 - indexPath.section)
When `completing` a `Todo`, lets move its cell to the start of the `completed` section, not the end. The UX's much better than the current state, as it's not entirely apparent what happened when the user taps an `active` `Todo` and completes it.

2018-08-02 07:26 UTC, dkulundzic commented on Marsiple/App/Todos/TodosViewController.swift
> +            todos[finishIndexPath.section].insert(removedTodo, at: finishIndexPath.row)
Lines `47`, `48`, `49` should not reside in the `performBatchUpdates` method - only `UITableView` mutating methods should reside within a `performBatchUpdates` call.

2018-08-02 07:26 UTC, dkulundzic commented on Marsiple/App/Todos/TodosViewController.swift
> +                                      completion: { _ in tableView.reloadData() })
I would like to see an `animated` reload of the affected `cell`, not a `static` `reloadData()` reload.

2018-08-02 07:26 UTC, dkulundzic commented on Marsiple/App/Todos/TodosViewController.swift
> +            tableView.reloadData()
I would like to see this `animated`. You can use `UITableView`'s cell-structure mutating methods for this.

2018-08-02 07:27 UTC, dkulundzic requested changes
Looks good, but an improvement is necessary.

2018-08-03 06:38 UTC, dkulundzic requested changes
The functionality and the UX are there 👍 , but I would like some code formatting changes, to improve readability.

2018-08-03 06:38 UTC, dkulundzic commented on Marsiple/App/Todos/TodosViewController.swift
> +                                      completion: { _ in tableView.reloadRows(at: [finishIndexPath], with: .automatic) })
Hmm, once again, I have to say that I don't appreciate the code formatting here. 

This is much more readable and concise:
```
tableView.performBatchUpdates({
      tableView.moveRow(at: indexPath, to: finishIndexPath)
}, completion: { _ in
      tableView.reloadRows(at: [finishIndexPath], with: .automatic)
})
```

2018-08-03 06:38 UTC, dkulundzic commented on Marsiple/App/Todos/TodosViewController.swift
>          }
As mentioned above, the code formatting could use more readability. 

```
tableView.performBatchUpdates({
      tableView.deleteRows(at: [indexPath], with: .automatic)
}, completion: nil)
```

2018-08-03 10:10 UTC, dkulundzic approved these changes
Looks great, lets 🚀

2018-08-03 11:41 UTC, merged

2018-08-03 11:42 UTC, matej494 commented
Successfully merged branch `todos/view` into branch `todos/main` without conflicts.